kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: kubewarden
  namespace: fleet-default
spec:
  repo: https://github.com/atoy3731/fleet-security-demo.git
  branch: rfed-us
  targets:
  - clusterGroup: secured
  paths:
  - "./kubewarden/cert-manager"
  - "./kubewarden/kubewarden/crds"
  - "./kubewarden/kubewarden/controller"
  - "./kubewarden/kubewarden/defaults"
  - "./kubewarden/kubewarden/policies"
