kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: airgapped-docs
  namespace: fleet-default
spec:
  repo: https://github.com/atoy3731/fleet-security-demo.git
  branch: rfed-us
  targets:
  - clusterGroup: carbide
  paths:
  - "./carbide/airgapped-docs/helm"
