kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: neuvector
  namespace: fleet-default
spec:
  repo: https://github.com/atoy3731/fleet-security-demo.git
  branch: azure-edge
  targets:
  - name: secured
    clusterSelector:
      matchLabels:
        security: enabled
  paths:
  - "./neuvector/crd"
  - "./neuvector/core"
